name: mirrorchyan_release_note

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
  release:
    types: [edited]

jobs:
  mirrorchyan:
    if: ${{ github.repository_owner == '1bananachicken' }}
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MaaNTE
          version_name: ${{ inputs.tag }}

          owner: 1bananachicken
          repo: MaaNTE
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
